language: julia

os:
  - linux

julia:
  - 1.0
  - 1.3
  - 1.4
  - nightly

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
