name = "IntrusiveCollections"
uuid = "fe54b08b-4815-4b70-8b1a-a3021f4307e7"
authors = ["Christian Rorvik <christian.rorvik@gmail.com>"]
version = "0.2.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
